/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insuranceCompany;

import javax.swing.JOptionPane;

/**
 *
 * @author ashutosh
 */
public class UpdateFormGUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateFormGUI
     */
    static ComprehensivePolicy chpPolicy;
    static ThirdPartyPolicy tppPolicy;

    static String policyType = "";

    static UserGUI userForm;
    UserGUI userForm1;
    
    public UpdateFormGUI(UserGUI userForm) {
        
        initComponents();
        this.userForm = userForm;
        this.userForm1 = userForm;
        loadCarType();
        

    }
    
  
    public void fillFormTPP(ThirdPartyPolicy policy) {

        policyType = "TPP";

        policyTypeText.setText("Third Party Policy");
        panelTPP.show();
        panelCHP.hide();

        policyNameBox.setText(policy.policyHolderName);

        //car
        carModelBox.setText(policy.car.getModel());
        carYearBox.setText(String.valueOf(policy.car.getManufacturingYear()));
        carTypeBox.setSelectedItem(String.valueOf(policy.getCar().getCarType()));
        priceBox.setText(String.valueOf(policy.car.getPrice()));

        claimBox.setText(String.valueOf(policy.numberOfClaims));

        dateBox.setText(String.valueOf(policy.getExpiryDate().getDay()));
        monthBox.setText(String.valueOf(policy.getExpiryDate().getMonth()));
        yearBox.setText(String.valueOf(policy.getExpiryDate().getYear()));

        commentBox.setText(policy.comments);
        
        
        tppPolicy = policy;
        
        

    }

    public void fillFormCHP(ComprehensivePolicy policy) {

        policyType = "CHP";
        policyTypeText.setText("Comprehensive Policy");
        panelCHP.show();
        panelTPP.hide();

        policyNameBox.setText(policy.policyHolderName);

        //car
        carModelBox.setText(policy.car.getModel());
        carTypeBox.setSelectedItem(String.valueOf(policy.getCar().getCarType()));
        carYearBox.setText(String.valueOf(policy.car.getManufacturingYear()));
        priceBox.setText(String.valueOf(policy.car.getPrice()));

        claimBox.setText(String.valueOf(policy.numberOfClaims));

        dateBox.setText(String.valueOf(policy.getExpiryDate().getDay()));
        monthBox.setText(String.valueOf(policy.getExpiryDate().getMonth()));
        yearBox.setText(String.valueOf(policy.getExpiryDate().getYear()));

        driverAgeBox.setText(String.valueOf(policy.driverAge));
        levelBox.setText(String.valueOf(policy.level));
        
        chpPolicy = policy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPolicy = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        policyNameBox = new javax.swing.JTextField();
        claimBox = new javax.swing.JTextField();
        panelCHP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        driverAgeBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        levelBox = new javax.swing.JTextField();
        panelTPP = new javax.swing.JPanel();
        commentBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        policyTypeText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        carModelBox = new javax.swing.JTextField();
        carTypeBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        priceBox = new javax.swing.JTextField();
        carYearBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateBox = new javax.swing.JTextField();
        monthBox = new javax.swing.JTextField();
        yearBox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formClosed(evt);
            }
        });

        jLabel1.setText("Policy Holder Name");

        jLabel4.setText("Number Of Claims");

        jLabel2.setText("Driver Age");

        jLabel9.setText("Level");

        javax.swing.GroupLayout panelCHPLayout = new javax.swing.GroupLayout(panelCHP);
        panelCHP.setLayout(panelCHPLayout);
        panelCHPLayout.setHorizontalGroup(
            panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCHPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCHPLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCHPLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(driverAgeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCHPLayout.setVerticalGroup(
            panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCHPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(driverAgeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabel10.setText("Comment");

        javax.swing.GroupLayout panelTPPLayout = new javax.swing.GroupLayout(panelTPP);
        panelTPP.setLayout(panelTPPLayout);
        panelTPPLayout.setHorizontalGroup(
            panelTPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTPPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(commentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTPPLayout.setVerticalGroup(
            panelTPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTPPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(commentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel11.setText("Update Policy Form");

        jLabel12.setText("Policy Type");

        policyTypeText.setText("Policy Type");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(policyNameBox))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(policyTypeText)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(claimBox))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(policyNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claimBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(policyTypeText)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        carTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Car Type");

        jLabel3.setText("Car Model");

        jLabel7.setText("Manufacturing Year");

        jLabel8.setText("Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carYearBox)
                            .addComponent(priceBox)
                            .addComponent(carTypeBox, 0, 151, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carModelBox)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carModelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(carTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(carYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setText("Update Policy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Expire (DD/MM/YY)");

        jButton2.setBackground(new java.awt.Color(255, 0, 73));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPolicyLayout = new javax.swing.GroupLayout(AddPolicy);
        AddPolicy.setLayout(AddPolicyLayout);
        AddPolicyLayout.setHorizontalGroup(
            AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddPolicyLayout.createSequentialGroup()
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddPolicyLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(AddPolicyLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPolicyLayout.createSequentialGroup()
                                .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        AddPolicyLayout.setVerticalGroup(
            AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        switch (policyType) {

            case "TPP": {
                boolean x = updateTPP();
                if(x){
                JOptionPane.showMessageDialog(this, "Policy Updated Successfully !");
                this.dispose();
                }else{
                JOptionPane.showMessageDialog(this, "Some Error Occurred");
                }
                
            }
            break;
            case "CHP": {
                boolean x = updateCHP();
                if(x){
                JOptionPane.showMessageDialog(this, "Policy Updated Successfully !");
                this.dispose();
                }else{
                userForm.loadUser();
                JOptionPane.showMessageDialog(this, "Some Error Occurred");
                }
            }
            break;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formClosed
        // TODO add your handling code here:
        userForm1.repaint();
        userForm1.fillTable();
        userForm1.fillFilterTable();
    }//GEN-LAST:event_formClosed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFormGUI(userForm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPolicy;
    private javax.swing.JTextField carModelBox;
    private javax.swing.JComboBox<String> carTypeBox;
    private javax.swing.JTextField carYearBox;
    private javax.swing.JTextField claimBox;
    private javax.swing.JTextField commentBox;
    private javax.swing.JTextField dateBox;
    private javax.swing.JTextField driverAgeBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField levelBox;
    private javax.swing.JTextField monthBox;
    private javax.swing.JPanel panelCHP;
    private javax.swing.JPanel panelTPP;
    private javax.swing.JTextField policyNameBox;
    private javax.swing.JLabel policyTypeText;
    private javax.swing.JTextField priceBox;
    private javax.swing.JTextField yearBox;
    // End of variables declaration//GEN-END:variables

    private boolean updateTPP() {

        tppPolicy.setPolicyHolderName(policyNameBox.getText());
        
        String carModel = carModelBox.getText();
        String carTypeS = String.valueOf(carTypeBox.getSelectedItem());
        CarType type = CarType.valueOf(carTypeS);
        int manufacturingYear = Integer.parseInt(carYearBox.getText());
        double price = Double.parseDouble(priceBox.getText());
        Car car = new Car(carModel, type, manufacturingYear, price);
        
        
        tppPolicy.setCar(car);
        
        int numberOfClaims = Integer.parseInt(claimBox.getText());
        
        tppPolicy.setNumberOfClaims(numberOfClaims);

        int day = Integer.parseInt(dateBox.getText());
        int month = Integer.parseInt(monthBox.getText());
        int year = Integer.parseInt(yearBox.getText());
        
        MyDate expiryDate = new MyDate(day, month, year);
        
        tppPolicy.setExpiryDate(expiryDate);
        
        tppPolicy.setComments(commentBox.getText());

        return true;
    }

    private boolean updateCHP() {
        
        chpPolicy.setPolicyHolderName(policyNameBox.getText());
        
        String carModel = carModelBox.getText();
        
         String carTypeS = String.valueOf(carTypeBox.getSelectedItem());
         CarType type = CarType.valueOf(carTypeS);
        int manufacturingYear = Integer.parseInt(carYearBox.getText());
        double price = Double.parseDouble(priceBox.getText());
        Car car = new Car(carModel, type, manufacturingYear, price);
        
        
        chpPolicy.setCar(car);
        
        int numberOfClaims = Integer.parseInt(claimBox.getText());
        
        chpPolicy.setNumberOfClaims(numberOfClaims);

        int day = Integer.parseInt(dateBox.getText());
        int month = Integer.parseInt(monthBox.getText());
        int year = Integer.parseInt(yearBox.getText());
        
        MyDate expiryDate = new MyDate(day, month, year);
        
        chpPolicy.setExpiryDate(expiryDate);
        
        int driverAge = Integer.parseInt(driverAgeBox.getText());
        int level = Integer.parseInt(levelBox.getText());
        
        chpPolicy.setDriverAge(driverAge);
        chpPolicy.setLevel(level);
        
        return true;
    }
    
    private void loadCarType() {
        carTypeBox.addItem(String.valueOf(CarType.HATCH));
        carTypeBox.addItem(String.valueOf(CarType.LUX));
        carTypeBox.addItem(String.valueOf(CarType.SUV));
        carTypeBox.addItem(String.valueOf(CarType.SED));
    }
}
