/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insuranceCompany;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import javax.swing.Box;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashutosh
 */
public class UserGUI extends javax.swing.JFrame {

    static LoginGUI lgui;
    static AdminGUI adminUI;
    static User user;
    /**
     * Creates new form UserGUI
     */
    public UserGUI(User user, LoginGUI ui) {
        initComponents();
        this.lgui=ui;
        this.user = user;
        loadUser();
        fillTable();
        fillFilterTable();
        loadCarType();
        panelCHP.hide();
        
        closeButton.hide();
    }

    public UserGUI(User user, AdminGUI ui) {
        initComponents();
        this.adminUI=ui;
        this.user = user;
        loadUser();
        fillTable();
        fillFilterTable();
        loadCarType();
        panelCHP.hide();
        
        logoutBTN.hide();
        closeButton.show();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        policyType = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Policies = new javax.swing.JPanel();
        subjectPanel = new javax.swing.JScrollPane();
        policiesTable = new javax.swing.JTable();
        updatePolicyBtn = new javax.swing.JButton();
        deletePolicyBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        AddPolicy = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        policyNameBox = new javax.swing.JTextField();
        claimBox = new javax.swing.JTextField();
        panelCHP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        driverAgeBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        levelBox = new javax.swing.JTextField();
        panelTPP = new javax.swing.JPanel();
        commentBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tppBTN = new javax.swing.JRadioButton();
        chpBTN = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        carModelBox = new javax.swing.JTextField();
        carTypeBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        priceBox = new javax.swing.JTextField();
        carYearBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateBox = new javax.swing.JTextField();
        monthBox = new javax.swing.JTextField();
        yearBox = new javax.swing.JTextField();
        PolicyReports = new javax.swing.JPanel();
        subjectPanel1 = new javax.swing.JScrollPane();
        filterPoliciesTable = new javax.swing.JTable();
        filterSearchBtn = new javax.swing.JButton();
        FilterCarModelBox = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        filterSearchBtn1 = new javax.swing.JButton();
        findPolicy = new javax.swing.JPanel();
        policyIDBox = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        findPolicyResult = new javax.swing.JTextArea();
        MyAccount = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        userIDBox = new javax.swing.JTextField();
        userPassBox = new javax.swing.JTextField();
        userNameBox = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        cityBox = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        suburbBox = new javax.swing.JTextField();
        streetBox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        userSrtNoBox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        logoutBTN = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(645, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onWindowClose(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(645, 300));

        Policies.setMinimumSize(new java.awt.Dimension(645, 370));

        policiesTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        policiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        policiesTable.setFillsViewportHeight(true);
        policiesTable.setPreferredSize(new java.awt.Dimension(200, 100));
        subjectPanel.setViewportView(policiesTable);

        updatePolicyBtn.setText("Update");
        updatePolicyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePolicyBtnActionPerformed(evt);
            }
        });

        deletePolicyBtn.setBackground(new java.awt.Color(255, 0, 73));
        deletePolicyBtn.setForeground(new java.awt.Color(255, 255, 255));
        deletePolicyBtn.setText("Delete");
        deletePolicyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePolicyBtnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel23.setText("All Policies");

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PoliciesLayout = new javax.swing.GroupLayout(Policies);
        Policies.setLayout(PoliciesLayout);
        PoliciesLayout.setHorizontalGroup(
            PoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliciesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(PoliciesLayout.createSequentialGroup()
                        .addComponent(updatePolicyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletePolicyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PoliciesLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PoliciesLayout.setVerticalGroup(
            PoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliciesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(subjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PoliciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePolicyBtn)
                    .addComponent(updatePolicyBtn)
                    .addComponent(jButton7))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Policies", Policies);

        jLabel1.setText("Policy Holder Name");

        jLabel4.setText("Number Of Claims");

        jLabel2.setText("Driver Age");

        jLabel9.setText("Level");

        javax.swing.GroupLayout panelCHPLayout = new javax.swing.GroupLayout(panelCHP);
        panelCHP.setLayout(panelCHPLayout);
        panelCHPLayout.setHorizontalGroup(
            panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCHPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCHPLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCHPLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(driverAgeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCHPLayout.setVerticalGroup(
            panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCHPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(driverAgeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabel10.setText("Comment");

        javax.swing.GroupLayout panelTPPLayout = new javax.swing.GroupLayout(panelTPP);
        panelTPP.setLayout(panelTPPLayout);
        panelTPPLayout.setHorizontalGroup(
            panelTPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTPPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(commentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTPPLayout.setVerticalGroup(
            panelTPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTPPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(commentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        policyType.add(tppBTN);
        tppBTN.setSelected(true);
        tppBTN.setLabel("Third Party Policy");
        tppBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tppBTNActionPerformed(evt);
            }
        });

        policyType.add(chpBTN);
        chpBTN.setLabel("Comprehensive Policy");
        chpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpBTNActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel20.setText("Create Policy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(policyNameBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(claimBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tppBTN)
                                .addGap(9, 9, 9)
                                .addComponent(chpBTN))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(policyNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claimBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chpBTN)
                    .addComponent(tppBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        carTypeBox.setModel(carTypeBox.getModel());
        carTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Car Type");

        jLabel3.setText("Car Model");

        jLabel7.setText("Manufacturing Year");

        jLabel8.setText("Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carYearBox)
                            .addComponent(priceBox)
                            .addComponent(carTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carModelBox)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carModelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(carTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(carYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setText("Add Policy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 73));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset From");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Expire (DD/MM/YY)");

        javax.swing.GroupLayout AddPolicyLayout = new javax.swing.GroupLayout(AddPolicy);
        AddPolicy.setLayout(AddPolicyLayout);
        AddPolicyLayout.setHorizontalGroup(
            AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPolicyLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddPolicyLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addGroup(AddPolicyLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddPolicyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddPolicyLayout.setVerticalGroup(
            AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(53, 53, 53))
            .addGroup(AddPolicyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Policy", AddPolicy);

        PolicyReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadPolicyFilters(evt);
            }
        });

        filterPoliciesTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        filterPoliciesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        filterPoliciesTable.setFillsViewportHeight(true);
        filterPoliciesTable.setPreferredSize(new java.awt.Dimension(200, 100));
        subjectPanel1.setViewportView(filterPoliciesTable);

        filterSearchBtn.setText("Filter");
        filterSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSearchBtnActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel24.setText("Car Model");

        filterSearchBtn1.setBackground(new java.awt.Color(102, 102, 255));
        filterSearchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        filterSearchBtn1.setText("Remove Filter");
        filterSearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSearchBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PolicyReportsLayout = new javax.swing.GroupLayout(PolicyReports);
        PolicyReports.setLayout(PolicyReportsLayout);
        PolicyReportsLayout.setHorizontalGroup(
            PolicyReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PolicyReportsLayout.createSequentialGroup()
                .addGroup(PolicyReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PolicyReportsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subjectPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                    .addGroup(PolicyReportsLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FilterCarModelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterSearchBtn1)))
                .addContainerGap())
        );
        PolicyReportsLayout.setVerticalGroup(
            PolicyReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PolicyReportsLayout.createSequentialGroup()
                .addGroup(PolicyReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel24)
                    .addComponent(FilterCarModelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterSearchBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        FilterCarModelBox.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Filter Policies", PolicyReports);

        policyIDBox.setToolTipText("");
        policyIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyIDBoxActionPerformed(evt);
            }
        });

        jLabel19.setText("Enter Policy ID");

        jButton3.setText("Search ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 73));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        findPolicyResult.setColumns(20);
        findPolicyResult.setRows(5);
        jScrollPane1.setViewportView(findPolicyResult);

        javax.swing.GroupLayout findPolicyLayout = new javax.swing.GroupLayout(findPolicy);
        findPolicy.setLayout(findPolicyLayout);
        findPolicyLayout.setHorizontalGroup(
            findPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPolicyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(findPolicyLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(policyIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        findPolicyLayout.setVerticalGroup(
            findPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPolicyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(policyIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(findPolicyLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton4)
                .addGap(300, 300, 300))
        );

        jTabbedPane1.addTab("Find Policy", findPolicy);

        jLabel11.setText("UserID");

        jLabel12.setText("Password");

        jLabel13.setText("Name");

        userIDBox.setEditable(false);
        userIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDBoxActionPerformed(evt);
            }
        });

        userNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameBoxActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Save Changes");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("City");

        jLabel17.setText("Suburb");

        jLabel16.setText("Street");

        jLabel15.setText("Street No");

        jLabel14.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel14.setText("Address");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userSrtNoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suburbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(172, 172, 172))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(userSrtNoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(streetBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(suburbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel22.setText("Your Account Deatils");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userPassBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userIDBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel22))
                .addGap(0, 216, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(userNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPassBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout MyAccountLayout = new javax.swing.GroupLayout(MyAccount);
        MyAccount.setLayout(MyAccountLayout);
        MyAccountLayout.setHorizontalGroup(
            MyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MyAccountLayout.setVerticalGroup(
            MyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("My Account", MyAccount);

        logoutBTN.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        logoutBTN.setText("Logout");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Insurance Policy Management Solution");

        closeButton.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        closeButton.setText("Close Form");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBTN)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBTN)
                    .addComponent(closeButton)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Filter Policies");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        updateUser();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void userNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameBoxActionPerformed

    private void userIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDBoxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        findPolicyResult.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(policyIDBox.getText());
        InsurancePolicy x = user.findPolicy(id);

        if(x!=null){
            findPolicyResult.setText(x.toFancyString());
        }else{

            findPolicyResult.setText("    No Such Policy Found With ID "+id+" !");

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void policyIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policyIDBoxActionPerformed

    private void loadPolicyFilters(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadPolicyFilters
        // TODO add your handling code here:

    }//GEN-LAST:event_loadPolicyFilters

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        clearPolicyForm();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        createPolicy();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeBoxActionPerformed

    private void chpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpBTNActionPerformed
        // TODO add your handling code here:
        panelCHP.show();
        panelTPP.hide();
    }//GEN-LAST:event_chpBTNActionPerformed

    private void tppBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tppBTNActionPerformed
        // TODO add your handling code here:
        panelTPP.show();
        panelCHP.hide();

    }//GEN-LAST:event_tppBTNActionPerformed

    private void deletePolicyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePolicyBtnActionPerformed
        // TODO add your handling code here:

        try
        {
            int row = policiesTable.getSelectedRow();
            String policy = policiesTable.getValueAt(row, 0).toString() ;

            int policyID = Integer.parseInt(policy);
            //JOptionPane.showMessageDialog(this,policyID);

            boolean result = user.deletePolicy(policyID);
            if (result){
                fillTable();
            }else{
                JOptionPane.showMessageDialog(this, "This policy cannot be deleted.");
            }

        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(this, "Please select the corresponding policy and then press Delete button.");
        }

    }//GEN-LAST:event_deletePolicyBtnActionPerformed

    private void updatePolicyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePolicyBtnActionPerformed
        // TODO add your handling code here:

        try
        {
            int row = policiesTable.getSelectedRow();
            String policyText = policiesTable.getValueAt(row, 0).toString() ;

            int policyID = Integer.parseInt(policyText);

            InsurancePolicy policy = user.findPolicy(policyID);
            String policyType = policy.policyType();

            UpdateFormGUI x = new UpdateFormGUI(this);

            if (policy!=null){

                switch(policyType){

                    case "TPP" : {
                        x.fillFormTPP((ThirdPartyPolicy) policy);
                        x.show();
                        fillTable();
                    }
                    break;
                    case "CHP" : {
                        x.fillFormCHP((ComprehensivePolicy) policy);
                        x.show();
                        fillTable();
                    }
                    break;
                    default : {
                        JOptionPane.showMessageDialog(this, "Something went wrong : (.");
                    }

                }

            }else{
                JOptionPane.showMessageDialog(this, "This policy cannot be updated.");
            }

        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(this, "Please select the corresponding policy and then press Update button.");
        }

    }//GEN-LAST:event_updatePolicyBtnActionPerformed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        lgui.show();
       this.dispose();
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        fillTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void filterSearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterSearchBtn1ActionPerformed
        // TODO add your handling code here:
        fillFilterTable();
    }//GEN-LAST:event_filterSearchBtn1ActionPerformed

    private void filterSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterSearchBtnActionPerformed
        // TODO add your handling code here:;
        filterPolicyTable();
    }//GEN-LAST:event_filterSearchBtnActionPerformed

    private void onWindowClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClose
        // TODO add your handling code here:
        if(lgui!=null){
        lgui.repaint();
        lgui.fetchUsers();
        }
        
        if(adminUI!=null){
        adminUI.repaint();
        adminUI.fillUserTable();
        adminUI.loadCompany();
        }
      
    }//GEN-LAST:event_onWindowClose

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_closeButtonActionPerformed

    
    
    
    public void loadUser(){
    
       userIDBox.setText(user.getUserID()+"");
       userNameBox.setText(user.getName());
       userPassBox.setText(user.getUserPassword());
       
       userSrtNoBox.setText(user.getAddress().getStreetNum()+"");
       streetBox.setText(user.getAddress().getStreet());
       suburbBox.setText(user.getAddress().getSuburb());
       cityBox.setText(user.getAddress().getCity());
    }
    
    public void clearPolicyForm(){
            
        policyNameBox.setText("");
        commentBox.setText("");
        claimBox.setText("");
        priceBox.setText("");
        levelBox.setText("");
        carModelBox.setText("");
        carYearBox.setText("");
        driverAgeBox.setText("");
        dateBox.setText("");
        monthBox.setText("");
        yearBox.setText("");
    
    }
    
    
    public void updateUser(){
    
       user.setName(userNameBox.getText()) ;
       user.setPassword(userPassBox.getText());
       

       
       int StreetNo = Integer.parseInt(userSrtNoBox.getText());
       String street = streetBox.getText();
       String suburb = suburbBox.getText();
       String city = cityBox.getText();
               
       Address address = new Address(StreetNo, street, suburb, city);
       
       user.setAddress(address);
       
       JOptionPane.showMessageDialog(this, "Updated Successfully!");
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGUI(user, lgui).setVisible(true);
            }
        });
    }

    
     public void fillTable() 
    {
        //HashMap<Integer, InsurancePolicy> policiesList = user.policies;
        //ArrayList<InsurancePolicy> policy = new ArrayList<InsurancePolicy>(policiesList.values());
        ArrayList<InsurancePolicy> policy = user.getPolicies();
        //Collections.sort();
        
        String [] header={"ID","Policy Holder Name","Car","Expiring (DD/MM/YY)","Total Premium"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        policiesTable.setModel(model);
        
        for(InsurancePolicy x : policy)
        {
            String[] row=new String[5];
            row[0] = x.policyID+"";
            row[1] = x.policyHolderName;
            row[2] = (x.car.getModel()+" Price : "+x.car.getPrice());
            row[3] = (x.getExpiryDate().getDay()+"/"+x.getExpiryDate().getMonth()+"/"+x.getExpiryDate().getYear());
            row[4] = x.calcPremium(1)+"";
            model.addRow(row);
        }   
    }
     
     
     
     
     
     public void createPolicy(){
     
         String policyHolderName = policyNameBox.getText();
         int id = Integer.parseInt(InsuranceCompany.genPolicyID());
         
         String carModel = carModelBox.getText();
         String carTypeS = String.valueOf(carTypeBox.getSelectedItem());
         CarType type = CarType.valueOf(carTypeS);
         int manufacturingYear = Integer.parseInt(carYearBox.getText());
         double price = Double.parseDouble(priceBox.getText());
         Car car = new Car(carModel, type, manufacturingYear, price);
      
         
         int numberOfClaims = Integer.parseInt(claimBox.getText());
                 
         int day = Integer.parseInt(dateBox.getText());
         int month = Integer.parseInt(monthBox.getText());
         int year = Integer.parseInt(yearBox.getText());
         
         MyDate expiryDate = new MyDate(day, month, year);
         
         
         if(tppBTN.isSelected()){
         //Creates Third Party Policy
         String comments = commentBox.getText();
         
          ThirdPartyPolicy policy = new ThirdPartyPolicy(policyHolderName, id, car, numberOfClaims, expiryDate, comments);
          boolean result = user.addPolicy(policy);
          
          if(result){
          JOptionPane.showMessageDialog(this, "Policy Added Successfully !");
          clearPolicyForm();
          fillTable();
          fillFilterTable();
          }else{
          JOptionPane.showMessageDialog(this, "Some Error Occurred !");
          }
          
          
         }
         if(chpBTN.isSelected()){
         //Creates Comprehensive Policy
         
          int level = Integer.parseInt(levelBox.getText());
          int driverAge = Integer.parseInt(driverAgeBox.getText());
         
         
          ComprehensivePolicy policy = new ComprehensivePolicy(policyHolderName, id, car, numberOfClaims, expiryDate, driverAge, level);
          boolean result = user.addPolicy(policy);
          
          if(result){
          JOptionPane.showMessageDialog(this, "Policy Added Successfully !");
          clearPolicyForm();
          fillTable();
          fillFilterTable();
          }else{
          JOptionPane.showMessageDialog(this, "Some Error Occurred !");
          }
         }
     
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPolicy;
    private javax.swing.JTextField FilterCarModelBox;
    private javax.swing.JPanel MyAccount;
    private javax.swing.JPanel Policies;
    private javax.swing.JPanel PolicyReports;
    private javax.swing.JTextField carModelBox;
    private javax.swing.JComboBox<String> carTypeBox;
    private javax.swing.JTextField carYearBox;
    private javax.swing.JRadioButton chpBTN;
    private javax.swing.JTextField cityBox;
    private javax.swing.JTextField claimBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField commentBox;
    private javax.swing.JTextField dateBox;
    private javax.swing.JButton deletePolicyBtn;
    private javax.swing.JTextField driverAgeBox;
    private javax.swing.JTable filterPoliciesTable;
    private javax.swing.JButton filterSearchBtn;
    private javax.swing.JButton filterSearchBtn1;
    private javax.swing.JPanel findPolicy;
    private javax.swing.JTextArea findPolicyResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField levelBox;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JTextField monthBox;
    private javax.swing.JPanel panelCHP;
    private javax.swing.JPanel panelTPP;
    private javax.swing.JTable policiesTable;
    private javax.swing.JTextField policyIDBox;
    private javax.swing.JTextField policyNameBox;
    private javax.swing.ButtonGroup policyType;
    private javax.swing.JTextField priceBox;
    private javax.swing.JTextField streetBox;
    private javax.swing.JScrollPane subjectPanel;
    private javax.swing.JScrollPane subjectPanel1;
    private javax.swing.JTextField suburbBox;
    private javax.swing.JRadioButton tppBTN;
    private javax.swing.JButton updatePolicyBtn;
    private javax.swing.JTextField userIDBox;
    private javax.swing.JTextField userNameBox;
    private javax.swing.JTextField userPassBox;
    private javax.swing.JTextField userSrtNoBox;
    private javax.swing.JTextField yearBox;
    // End of variables declaration//GEN-END:variables

    private void loadCarType() {
        carTypeBox.addItem(String.valueOf(CarType.HATCH));
        carTypeBox.addItem(String.valueOf(CarType.LUX));
        carTypeBox.addItem(String.valueOf(CarType.SUV));
        carTypeBox.addItem(String.valueOf(CarType.SED));
    }
    
    
        
     public void fillFilterTable(){
        //HashMap<Integer, InsurancePolicy> policiesList = user.policies;
        //ArrayList<InsurancePolicy> policy = new ArrayList<InsurancePolicy>(policiesList.values());
        ArrayList<InsurancePolicy> policy = user.getPolicies();
        //Collections.sort();
        
        String [] header={"ID","Policy Holder Name","Car","Expiring (DD/MM/YY)","Total Premium"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        filterPoliciesTable.setModel(model);
        
        for(InsurancePolicy x : policy)
        {
            String[] row=new String[5];
            row[0] = x.policyID+"";
            row[1] = x.policyHolderName;
            row[2] = (x.car.getModel());
            row[3] = (x.getExpiryDate().getDay()+"/"+x.getExpiryDate().getMonth()+"/"+x.getExpiryDate().getYear());
            row[4] = x.calcPremium(1)+"";
            model.addRow(row);
        }     
    }
     
     
    public void filterPolicyTable(){
      
        String carModel = FilterCarModelBox.getText();
        ArrayList<InsurancePolicy> policy = user.filterByCarModel(carModel);
        //Collections.sort();
        
        String [] header={"ID","Policy Holder Name","Car","Expiring (DD/MM/YY)","Total Premium"};
        DefaultTableModel model=new DefaultTableModel(header,0);
        filterPoliciesTable.setModel(model);
        
        for(InsurancePolicy x : policy)
        {
            String[] row=new String[5];
            row[0] = x.policyID+"";
            row[1] = x.policyHolderName;
            row[2] = (x.car.getModel());
            row[3] = (x.getExpiryDate().getDay()+"/"+x.getExpiryDate().getMonth()+"/"+x.getExpiryDate().getYear());
            row[4] = x.calcPremium(1)+"";
            model.addRow(row);
        }     
    }
    
   
}
